/* VARIAVEL COMPOSTA */
//VARIAVEL COMPOSTA É A VARIAVEL QUE TEM VARIOS ELEMENTOS, CADA ELEMENTO É COMPOSTO POR SEU VALOR E POR UMA CHAVE DE IDENTIFICAÇÃO

var num = [5,9,8,2,3]//A IDENTIFICAÇÃO DE CADA ELEMENTO FICA POR SUA POSIÇÃO NO VETOR 

num[5] = 6//'LET NUM NO QUINTO ELEMENTO DO VETOR' ,RECEBE "6"

num.push(7)//VAR NUM CRIA UM ULTIMO ELEMENTO DO VETOR,E RECEBE 7 

num.sort()//ELE ORGANIZA EM ORDEM CRESCENTE

num.indexOf(5)//EU PEGUNTO SE TEM O ELEMENTO ESCOLHIDO(NO CASO 5), SE SIM ELE ME FALA SUA POSIÇÃO

num.indexOf(7)//EU PERGUNTO SE TEM O ELEMENTO ESCOLHIDO(NO CASO 7) , SE NÃO ELE ME RESPONDE "-1"

console.log(`Tem numero 5? se sim qual é a posição dele  ${num.indexOf(5)}`)

console.log(`A quantidade de elementos no vetor é igual a ${num.length}`)//(VARIAVEL.LENGTH) DIZ QUANTOS ELEMENTOS TEM NO VETOR . OBS:NESSE A ORDEM NÃO INFLUENCIA, CONTA NORMAL.

console.log(`As variaveis são ${num}`)

/* 
EXEMPLO DE COMO É CONTADO AS SUAS POSIÇÕES
0°==5,
1°==9,
2°==8,
3°==2,
4°==3
 */